### ISSUE TITLE
Critical: unable to send a message

### ISSUE THREAD

**Issue by hagitmer** [Hacknocraft/AppFriendsUI#10]
Sometimes, a message cannot be sent.

In this case, a user was trying to send a message and kept getting an error. 
After quitting the app and relaunching, he was able to send a new message although the original failed message _would not send_. See attached video.
[failedmessage.mov.zip](https://github.com/Hacknocraft/AppFriendsUI/files/746407/failedmessage.mov.zip)

**Comment by laeroah** [comment]
any dev -> production or app id switch happen while you were using the app?

**Comment by laeroah** [comment]
We will try to reproduce, but if there's any more information you could provide, it'd help

**Comment by hagitmer** [comment]
@laeroah it was on production the whole time and there was no environment switching. Let me know if there's any other information I can provide.

**Comment by laeroah** [comment]
@hagitmer our QA tried to reproduce this situation for a few days, but couldn't. 
If you still have the conversation saved on your phone, I can take a look at it while I'm in the office. 
It would be even better if you can reproduce it.
