### ISSUE TITLE
High: Unable to Reply to Group Convo

### ISSUE THREAD

**Issue by hagitmer** [Hacknocraft/AppFriendsUI#11]
If a user is on their lock screen > then added to a group conversation > then receives a push notification for having been added >  the user cannot send a message to the group until they close and reopen the convo

**Steps to Recreate:**

User A on Device X
User B on Device Y

> 1) Log into the app with B on Y, then go to the lock screen
> 2) From A on X, create a group convo and include user B
> 3) From B on Y, open the push notification for the user being added to that group
> 4) From B on Y, try to send a message in that group convo

**Notice** that the user will not be able to send the message as the app will display the error icon next to the message until the user closes the conversation and reopens it.

**Expected Behavior:** The user can send a message immediately after opening that initial push notification that alerts them they were added to a new group conversation.

**Comment by laeroah** [comment]
This is the same problem as the 1:1 conv push. Will be fixed in the up coming release.
