### ISSUE TITLE
High: Support Swift 3.1

### ISSUE THREAD

**Issue by hagitmer** [Hacknocraft/AppFriendsUI#14]
Currently it seems that Socket.IO fails to build but there might be other issues.
It would be great if you can update on the ETA for supporting Swift 3.1.

Thanks.

**Comment by laeroah** [comment]
Will confirm this next week.

**Comment by laeroah** [comment]
A sample app using Swift3.1, xcode8.3 can be found here:
https://github.com/Hacknocraft/AppFriendsiOSSample/tree/swift3.1

**Comment by hagitmer** [comment]
@laeroah anything we need to do on our end besides the SDK merge?

**Comment by laeroah** [comment]
no, just integrate the new SDK will be enough.
