### ISSUE TITLE
Public API re-vamp

### ISSUE THREAD

**Issue by laeroah** [Hacknocraft/AppFriendsUI#20]
Refactor public api so that the developers have easier time and consistent experience using the SDK.

**Comment by hagitmer** [comment]
@laeroah what will be the impact for GC?

**Comment by laeroah** [comment]
@hagitmer 
Once update to the latest SDK, will make some changes to the way some public apis are called. I expect the time to make these changes to be less than 1 hour.

**Comment by hagitmer** [comment]
Thanks. Can you please let us know what version of SDK requires us to make this change on our end?

**Comment by laeroah** [comment]
we plan to release this update around mid March, and will have clear document on the changes and new API.
