### ISSUE TITLE
High: links do not open

### ISSUE THREAD

**Issue by hagitmer** [Hacknocraft/AppFriendsUI#21]
Links are no longer clickable and users are forced to copy and paste the link into a browser.

The ideal behavior is that a user taps on the link will get two options:
1. Open
2. View the Read Receipt

**Comment by laeroah** [comment]
@hagitmer please implement `override func linkTapped(_ cell: HCChatTableViewCell, url: URL) {` to handle open link in your app. This has not changed.
If the user long tap/hard tap the link, it will call this linkTapped method.
If you want to achieve the behavior you want, it's also possible by changing 
`override func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath)` in your chat view. This part is the in demo chat view we provided to you. It's open source and now part of your app, so you have total control over it.
