### ISSUE TITLE
Urgent: media button behavior has changed unexpectedly 

### ISSUE THREAD

**Issue by hagitmer** [Hacknocraft/AppFriendsUI#25]
1. Adding Photos & Video: Tapping on the media icon (on the left of the Enter Message field) should bring up an action sheet as it did before. Currently changes keyboard to show 2 icons for taking a picture and accessing photo library

2. The media icon should be a camera icon rather than a plus icon

**Comment by laeroah** [comment]
hi, this is intended. We need to bring up a menu sheet so it's possible to add more message types in the chat.

**Comment by hagitmer** [comment]
@laeroah more actions should be supported in a native format meaning an iOS action sheet

**Comment by laeroah** [comment]
Action sheet can get quickly overflown as we add more message types such as location. A lot of chat apps uses the keyboard areas to show more input options. I think it's actually a pretty standard UX.
That being said, if you want to use standard iOS actionsheet, you can certainly override our UI behavior and just use system actionsheet, and the icon of the button can be changed as well from your side. 
With public API re-vamping, we will be making it more flexible in the future. Let me know if you still want to change it or I could chat with a dev about how override can be done.

**Comment by hagitmer** [comment]
@laeroah I understand that you want to make it more robust for the future, but right now, there are only two types of actions available so I just want to make it extra simple for the user to select one and not guess what these icons mean. 
I don't think these icons fall into the "simple and clear" category. Also, I'm worried that we need to add more development time every time we upgrade a version for bug fixes.

**Comment by laeroah** [comment]
let's move the discussion on Slack. just ping me when you want to talk about this.
