### ISSUE TITLE
Critical: Messages weren't delivered to one specific user in the group

### ISSUE THREAD

**Issue by hagitmer** [Hacknocraft/AppFriendsUI#3]
Abhinav, Ron, Aman, and I were chatting in our PM group when Abhinav sent two messages that were received by me and Aman, however they never made it to Ron's phone (messages before and after were delivered properly).

The screenshots below show that two messages sent from Abhinav ("nope", guessing you're testing address recognition?") are missing in the second screenshot.

![hagit s screenshot](https://cloud.githubusercontent.com/assets/21039229/21121065/5e5112de-c098-11e6-8ba4-47d89427602a.jpg)

![slack for ios upload-1](https://cloud.githubusercontent.com/assets/21039229/21121059/512af34a-c098-11e6-9006-17d770a65c1d.jpg)

**Comment by hagitmer** [comment]
When sending a message to a large group (over 242 users), I'm noticing that the message first appears to be in a failed state (red exclamation mark icon). Only after a few seconds, the mark is cleared and the Seen By screen is available.

This creates a UX and performance issues with users since they think the message wasn't sent and will continue sending more and more.

**Comment by hagitmer** [comment]
The typing indication is inaccurate: even when users are still typing, the "x is typing" indication disappears a few seconds after the typing has begun.

**Comment by hagitmer** [comment]
The New Messages line doesn't appear if the user has more than 20 unread messages.
The New Messages line should appear, as the name suggests, even when there are more than 20 new messages so that users know what they've missed on and have context.

**Comment by laeroah** [comment]
investigating, but let us know if it happens again. Log the time, device, user account. Thank you.

**Comment by hagitmer** [comment]
User account: Ron Feldman
Device: iPhone 7
Time: 1:23pm EST on 12/12/16

**Comment by laeroah** [comment]
Thank you! I looked through the logs a long time yesterday, but haven't pinpoint the issue yet. I've asked our backend engineer to take a look at this. Our QA is also trying to reproduce. Will keep you posted on anything we find.
At the same time, if it ever happens again, please log it here. Any additional information will help.

**Comment by hagitmer** [comment]
Issue just happened again:
- we were messaging in our staging environment 
- many messages are not delivered to all members of the group. Screenshots below:
![Ron's screenshot]
(https://cloud.githubusercontent.com/assets/21039229/21243427/ccaad5b2-c2e6-11e6-8425-ff6a9c7068af.jpg)
![Aman's screenshot]
(https://cloud.githubusercontent.com/assets/21039229/21243440/dd8c7e08-c2e6-11e6-9fd5-ad76a3c0266d.png)
![Hagit's screenshot]
(https://cloud.githubusercontent.com/assets/21039229/21243556/579baf7a-c2e7-11e6-96e6-2d83c893d1a6.PNG)

**Comment by laeroah** [comment]
@hagitmer which messages was sent and not delivered? who sent it and who didn't receive the message?

**Comment by laeroah** [comment]
nvm. thanks for the screens

**Comment by laeroah** [comment]
Thanks, looking into this.

**Comment by laeroah** [comment]
@hagitmer We found an issue introduced by a recent patch to our server. We will fix it tonight. Will keep you posted. Thanks!

**Comment by laeroah** [comment]
Should be fixed. Please let me know if it happens again. Will close this ticket open in 2 weeks unless any more instance is found.

**Comment by hagitmer** [comment]
Thanks @laeroah. Will let you know if I see this again.

**Comment by laeroah** [comment]
this has been fixed.
