### ISSUE TITLE
Sending a message to massive audience initially reports as having failed to send

### ISSUE THREAD

**Issue by hagitmer** [Hacknocraft/AppFriendsUI#4]
When sending a message to a large group (over 242 users), I'm noticing that the message first appears to be in a failed state (red exclamation mark icon). Only after a few seconds, the failed mark is cleared and the Seen By screen is available.
This creates a UX and performance issues with users since they think the message wasn't sent and will continue sending more and more.

I think you might need to change the timeout period for when you display the failed message icon.

**Comment by laeroah** [comment]
this is fixed
