### ISSUE TITLE
New Messages line is missing when there are more than 20 unread messages

### ISSUE THREAD

**Issue by hagitmer** [Hacknocraft/AppFriendsUI#6]
The New Messages line doesn't appear if the user has more than 20 unread messages.
The New Messages line should appear, as the name suggests, even when there are more than 20 new messages so that users know what they've missed on and have context.

**Comment by laeroah** [comment]
This is working as expected right now. I explained that we can't load infinite number of messages up front just to display the new message line. Should we expand the initial loading from 20 to something a bit larger could be discussed and needed to be tested out.

**Comment by hagitmer** [comment]
This is not expected behavior IMO. New Messages label means New Messages, not Only If There Were Less Than 20 Messages, It's a New Messages Line.
It's a confusing and not consistent experience to the user, and it makes it impossible to follow long lively.

**Comment by laeroah** [comment]
we have to stop the UI at where the first new message is. It means we have to load all messages after that message. If there are 1000 messages, we'd have to load 1000. It would create a big lag to the user. 
However, if you scroll upwards, you will see the new message line when you get to the first new message sent to you. We can look into expanding the initial message load number to larger after we run tests against performance.

**Comment by laeroah** [comment]
fixed, now we load 40 messages up front. It will make the new message line more likely to appear

**Comment by laeroah** [comment]
resolved
