### ISSUE TITLE
Critical: log out clears all messages

### ISSUE THREAD

**Issue by hagitmer** [Hacknocraft/AppFriendsUI#7]
All messages history is cleared when a user logs out. When logging back in, the dialogs are available but the content is empty.
As discussed, we should display the last 100 messages per dialog when logging back in, including media.

**Comment by laeroah** [comment]
Ok. this is on the release road map in Jan.

**Comment by hagitmer** [comment]
You have previously mentioned early Jan. Do you have a more detailed ETA? Thanks

**Comment by laeroah** [comment]
I will be traveling until the 10th. 
should be able to finish it the week after I come back.

**Comment by laeroah** [comment]
This should have been resolved in the new version
