### ISSUE TITLE
Medium: Picture view - the share icon is not iOS icon

### ISSUE THREAD

**Issue by hagitmer** [Hacknocraft/AppFriendsUI#8]
The current icon used for involing the action sheet while viewing a picture is an Android icon rather than an iOS one.

![screen shot 2017-01-29 at 9 50 43 pm](https://cloud.githubusercontent.com/assets/21039229/22411023/223f1b10-e66d-11e6-9d80-4c77b5355e96.png)

![img_2060](https://cloud.githubusercontent.com/assets/21039229/22411029/2f2782e0-e66d-11e6-8f42-fdf656abe478.PNG)

**Comment by laeroah** [comment]
ok, we will change the icon.
